<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>

<p>
<div class="field regulation required">
    <label for="customtext" class="label"><span><?php /* @escapeNotVerified */
            echo __('customtext') ?></span></label>
    <div class="control">
        <input type="text"  name="customtext" id="customtext" title="<?php /* @escapeNotVerified */
        echo __('customtext') ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
	
</div>
</p></fieldset>